version: 0.0
os: linux
files:
   - source: war/
     destination: /var/lib/tomcat7/webapps/
hooks:
   BeforeInstall:
    - location: scripts/installtomcat.sh
      runas: root
    - location: scripts/installjava.sh
      runas: root
    - location: scripts/starttomcat.sh
      runas: root
   AfterInstall:
    - location: scripts/restarttomcat.sh
      runas: root

